name: CI
inputs:
  project:
    default: ''
runs:
  using: node20
  main:
  steps:
    - run: nx lint ${{ inputs.project }}
      shell: bash
    - run: nx build ${{ inputs.project }}
      shell: bash
