name: CI
inputs:
  project:
    default: ''
runs:
  using: composite
  steps:
    - run: npx nx lint ${{ inputs.project }}
      shell: bash
    - run: npx nx build ${{ inputs.project }}
      shell: bash
