name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm i
      - name: '@celm/core'
        uses: ./.github/actions/ci
        with:
          project: '@celm/core'
      - name: '@celm/jsx'
        uses: ./.github/actions/ci
        with:
          project: '@celm/jsx'
